INSTALL_TARGET_PROCESSES = SpringBoard


include $(THEOS)/makefiles/common.mk

TWEAK_NAME = TLinkIOSTweak

# Tweak files
# TLinkIOSTweak_FILES =  $(wildcard *.x) $(wildcard *.m)
TLinkIOSTweak_FILES =  $(wildcard *.x) $(wildcard *.m) ${wildcard ../common/*.m}

TLinkIOSTweak_CFLAGS = -fobjc-arc -Wno-error=unused-variable -Wno-error=unused-function -I../common  -I../include -D USES_LIBUNDIRECT=1 -D SUPPORT_IPAD=1 -D ENABLE_STATE_RESTORATION=1
TLinkIOSTweak_FRAMEWORKS = UIKit Foundation AdSupport UserNotifications IOKit Security CoreLocation CoreFoundation Network CoreTelephony SystemConfiguration WebKit SafariServices   
TLinkIOSTweak_PRIVATE_FRAMEWORKS = MobileCoreServices AppSupport SpringBoardServices 
TLinkIOSTweak_LIBRARIES = MobileGestalt

# CRITICAL: Force ObjC runtime to properly initialize +load methods
# -lobjc ensures libobjc is linked, -ObjC forces all ObjC symbols to be loaded
TLinkIOSTweak_LDFLAGS = -lobjc -Wl,-ObjC

include $(THEOS_MAKE_PATH)/tweak.mk
